spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: internaute
          uri: lb://internaute
          predicates:
            - Path=/api/internautes/**
        - id: evenement
          uri: lb://evenement
          predicates:
            - Path=/api/evenements/**
        - id: categorie
          uri: lb://evenement
          predicates:
            - Path=/api/categories/**
        - id: ticket
          uri: lb://ticket
          predicates:
            - Path=/api/tickets/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
